### ISSUE TITLE
sourcing .bashrc

### ISSUE THREAD

**Issue by mheilman** [EducationalTestingService/gridmap#29]
My default shell is zsh.  If I create a .bashrc file with an incorrect, out-of-date DRMAA_LIBRARY_PATH variable, then jobs won't run.  This error shows up in the .e* log file:

```
Traceback (most recent call last):
  File "/opt/python/2.7/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/opt/python/2.7/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/opt/python/2.7/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/opt/python/2.7/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/opt/python/2.7/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/opt/python/2.7/lib/python2.7/site-packages/gridmap/__init__.py", line 69, in <module>
    from gridmap.conf import (CHECK_FREQUENCY, CREATE_PLOTS, DEFAULT_QUEUE,
  File "/opt/python/2.7/lib/python2.7/site-packages/gridmap/conf.py", line 76, in <module>
    import drmaa
  File "build/bdist.linux-x86_64/egg/drmaa/__init__.py", line 63, in <module>
  File "build/bdist.linux-x86_64/egg/drmaa/session.py", line 39, in <module>
  File "build/bdist.linux-x86_64/egg/drmaa/helpers.py", line 36, in <module>
  File "build/bdist.linux-x86_64/egg/drmaa/wrappers.py", line 56, in <module>
  File "/opt/python/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /local/research/linux/sge6_2u6/lib/lx24-amd64/libdrmaa.so: cannot open shared object file: No such file or directory
```

So, it looks like the grid engine is sourcing the system default shell's rc file, even though it shouldn't be sourcing anything.

A temporary solution was to just delete the .bashrc file (or update it to use the correct path as well as the .zshrc file).

**Comment by dan-blanchard** [comment]
I'm not sure there's anything we can do at the GridMap level for this. I think it's probably an issue with how SGE was configured.
